### PR TITLE
1 donation tracker component part 1

### PR DESCRIPTION
**Pull request by bdelrosario1**
Finished stage one of donation tracker portion of project. Please review my code

### CODE REVIEW

**Review by jimmytran2 — APPROVED** [review]
Looks good. Please remember to add param type in docstrings

**Comment by bdelrosario1** [comment]
> Looks good. Please remember to add param type in docstrings

Updated my docstrings

**Review by jimmytran2 — APPROVED** [review]
Docstring changes look good

**Review by mdoerksen — APPROVED** [review]
Everything looks good! Great work.

**Pull request merged**
