### PR TITLE
2 volunteer hours tracker component part 1

### PR DESCRIPTION
**Pull request by mdoerksen**
Created a volunteer tracker form that users can log which charity theyre volunteering for, how many hours, the date of volunteering and their experience from 1-5. Ran the functions through testing using jest and all tests passed.

### CODE REVIEW

**Review by jimmytran2 — CHANGES_REQUESTED** [review]
Looks good, just missing junit from package.json

**Review by bdelrosario1 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

**Comment by mdoerksen** [comment]
> Looks good, just missing junit from package.json

I added the changes to the package.json file!

**Review by jimmytran2 — APPROVED** [review]
package.json files looks good

**Review by bdelrosario1 — APPROVED** [review]
Look great, good job adding workflow

**Pull request merged**
